config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    namespace :devise do
      get 'sign_out', to: 'sessions#destroy'
    end
  end

  root to: 'home#index'

  resources :articles

  namespace :front do
    resources :articles, only: %i(index)
  end

  namespace :vue do
    resources :articles, only: %i(index show new edit) do
      resources :comments, only: %i(index new)
    end
  end

  namespace :api do
    namespace :v1 do
      resources :articles do
        resources :comments, only: %i(index create)
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  has_many :tags, -> { order('display_order ASC') }, dependent: :destroy, inverse_of: :article
  accepts_nested_attributes_for :tags, reject_if: :all_blank, allow_destroy: true

  belongs_to :user

  delegate :email, to: :user, prefix: :author

  validates :title, presence: true
  validates :body, presence: true
  validate :after_today

  has_one_attached :image

  before_validation :before_validation_test, :downcase_str_value
  after_validation :after_validation_test
  before_create :before_create_test
  after_create :after_create_test, :create_comment
  before_save :before_save_test
  after_save :after_save_test

  def after_today
    # date_valueが今日以降の日付かチェックしてエラーならエラーメッセージをセットする
  end

  def before_validation_test
    self.range_value = range_value.upcase if range_value.present?
  end

  def after_validation_test
  end

  def before_create_test
  end

  def after_create_test
  end

  def before_save_test
  end

  def after_save_test
  end

  def create_comment
    comments.create!(body: '記事コメント')
  end

  def downcase_str_value
    self.str_value = str_value.downcase
  end

  def short_body
    body.truncate(20)
  end

  def comment_count
    comments.count
  end

  def created_on
    created_at.to_date
  end

  def image_url
    return unless image.attached?
    path = Rails.application.routes.url_helpers.rails_blob_path(image, only_path: true)
    "http://localhost:3000#{path}"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :body, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :article

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ApplicationController
  protect_from_forgery with: :null_session
  skip_before_action :authenticate_user!
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < Api::V1::ApplicationController
  before_action :set_article, only: %i[update show destroy]
  
  def index
    articles = Article.all.order(created_at: :desc).page(params[:page]).per(10)
    render json: articles.to_json(only: %i[id title], methods: %i[short_body author_email comment_count created_on])
  end

  def create
    article = Article.new(article_params)

    if article.save
      render json: article.to_json
    else
      render json: { errors: article.errors.full_messages }
    end
  end

  def update
    if @article.update(article_params)
      render json: @article.to_json
    else
      render json: { title: @article.title, body: @article.body, errors: @article.errors.full_messages }
    end
  end

  def show
    render json: @article.to_json(include: [tags: { only: %i[name]}], methods: %i[author_email comment_count image_url])
  end

  def destroy
    if @article.destroy
      render json: @article.to_json
    else
      render json: { errors: @article.errors.full_messages, status: :unprocessable_entity }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :user_id, tags_attributes: %i[id name display_order _destroy])
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::ApplicationController
  before_action :set_article, only: %i[index create]
  
  def index
    comments = @article.comments.order(created_at: :desc)
    render json: comments.to_json(only: %i[id body created_at])
  end

  def create
    comment = @article.comments.build(comment_params)

    if comment.save
      render json: comment.to_json
    else
      render json: { errors: comment.errors.full_messages }
    end
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit update show destroy]

  def index
   @articles_search = Search::Articles.run(params.fetch(:search_articles, {}))
   if @articles_search.valid?
     @articles = @articles_search.result.page(params[:page])
   else
     flash.now[:alert] = '指定の検索が動作しませんでした。'
     @articles = Article.all.order(created_at: :desc).page(params[:page])
   end
  end

  def new
    @article = Article.new
    @article.tags.build
  end

  def create
    inputs = params.fetch(:article, {}).merge(user: current_user)
    outcome = Articles::Create.run(inputs)
    if outcome.valid?
      redirect_to articles_path, notice: '登録しました。'
    else
      @article = outcome
      flash.now[:alert] = "登録に失敗しました。#{@article.errors.full_messages.join('。')}"
      render :new
    end
  end
  
  def edit
    @article.tags.build if @article.tags.empty?
  end
  
  def update
    inputs = params.fetch(:article, {}).merge(article: @article)
    outcome = Articles::Update.run(inputs)
    if outcome.valid?
      redirect_to articles_path, notice: '更新しました。'
    else
      @article = outcome
      flash.now[:alert] = "更新に失敗しました。\n#{@article.errors.full_messages.to_sentence}"
      render :edit
    end
  end

  def show
  end

  def destroy
    outcome = Articles::Delete.run(article: @article)
    if outcome.valid?
      redirect_to articles_path, notice: '削除しました'
    else
      redirect_to articles_path, alert: "削除に失敗しました。#{outcome.errors.full_messages.join('。')}"
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :image, tags_attributes: %i[id name display_order _destroy])
  end
end

app/controllers/front/articles_controller.rb
class Front::ArticlesController < ApplicationController
  def index
    @articles = Article.order(created_at: :desc)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @comments = Comment.all
  end
end

app/controllers/vue/articles_controller.rb
class Vue::ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit]

  def index
    @articles = Article.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show; end

  def new; end

  def edit; end

  private

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/vue/comments_controller.rb
class Vue::CommentsController < ApplicationController
  before_action :set_article, only: %i[index new]

  def index; end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_controller?(controller_name)
    params[:controller] == controller_name ? 'active' : nil
  end
end

app/helpers/practice_helper.rb
module PracticeHelper

  def map_sample(prefectures)
    # mapメソッドを使って都道府県名の配列を作ろう

  end

  def inject_sample(prefectures)
    # injectメソッドを使って各都道府県のcountを集計してみよう

  end

  def join_sample(prefectures)
    # joinメソッドを使って各都道府県の名称(name)をカンマ区切りで繋げてみよう

  end

  def select_sample(prefectures)
    # selectメソッドを使って人口数(count)が4000000より大きい県名を取得しよう

  end

  def group_by_sample(prefectures)
    # group_byメソッドを使ってidでグループ分けしてみよう

  end

  def to_h_sample(prefectures)
    # to_hメソッドを使って都道府県名(name)をキー、countがバリューのHashを作ろう

  end
end

app/views/application/_head_tag_content.html.haml
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%meta{:charset => "utf-8"}/
%meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
%meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
/ HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
/ WARNING: Respond.js doesn't work if you view the page via file://
/ [if lt IE 9]
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js" />
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js" />
/ Google Font
%link{:href => "https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic", :rel => "stylesheet"}/

app/views/application/_nav_header.html.haml
%header.main-header
  %a.logo{:href => "/"}
    %span.logo-lg
      %b> Qiitan
      Training
  %nav.navbar.navbar-static-top{:role => "navigation"}
    %a.sidebar-toggle{"data-toggle" => "push-menu", :href => "#", :role => "button"}
      %span.sr-only Toggle navigation
    - if user_signed_in?
      .navbar-custom-menu
        %ul.nav.navbar-nav
          %li
            = link_to current_user.email, root_path

app/views/application/_notice_alert.html.haml
- if notice.present?
  .notice-alert
    .alert.alert-success.alert-dismissible
      %button.close{type: "button",'data-dismiss': "alert", 'aria-hidden': "true"}
        ×
      %i.icon.fa.fa-check
      = notice

- if alert.present?
  .notice-alert
    .alert.alert-danger.alert-dismissible
      %button.close{type: "button",'data-dismiss': "alert", 'aria-hidden': "true"}
        ×
      %i.icon.fa.fa-warning
      = alert

app/views/application/_sidebar.html.haml
/ Left side column. contains the logo and sidebar
%aside.main-sidebar
  / sidebar: style can be found in sidebar.less
  %section.sidebar
    / Sidebar Menu
    %ul.sidebar-menu{ data: { widget: 'tree' }}
      %li{ class: "#{active_controller?('articles')}" }
        = link_to articles_path do
          %i.fa.fa-newspaper-o
          %span 記事一覧
      %li{ class: "#{active_controller?('vue/articles')}" }
        = link_to vue_articles_path do
          %i.fa.fa-newspaper-o
          %span 【Vue】記事一覧
      %li
        = link_to devise_sign_out_path do
          %i.fa.fa-sign-out
          %span ログアウト

app/views/articles/_form.html.haml
.box
  .box-body
    = simple_form_for article do |f|
      = f.input :title
      = f.input :body
      = f.input :image do
        - if f.object.image.attached?
          = image_tag f.object.image, height: 100
        = f.input_field :image, as: :file, accept: 'image/*'
      .form-group
        %label タグ
        .row
          .col-sm-5
            %span 名前
          .col-sm-2
            %span 順番
          .col-sm-5
            %span
      = f.simple_fields_for :tags do | g |
        = g.input :id, as: :hidden
        = render 'articles/tag_fields', f: g
      .links
        = link_to_add_association f, :tags, partial: 'articles/tag_fields' do
          %button.btn.btn-info
            %i.fa.fa-plus-circle
              %strong
                %small タグ追加
      .actions
        = f.submit class: 'btn btn-primary'

app/views/articles/_order_link.html.haml
- if form_object.order_by != order_by
  = link_to send(url_method, search_articles: { order_by: order_by, order_direction: :asc }) do
    %i.fa.fa-sort.fa-lg
- elsif form_object.order_direction == :asc
  = link_to send(url_method, search_articles: { order_by: order_by, order_direction: :desc }) do
    %span{style: 'color:ORANGE'}
      %i.fa.fa-sort-desc.fa-lg
- else # form_object.order_direction == :desc
  = link_to send(url_method, search_articles: { order_by: order_by, order_direction: :asc }) do
    %span{style: 'color:ORANGE'}
      %i.fa.fa-sort-asc.fa-lg

app/views/articles/_search_form.html.haml
.row
  = simple_form_for articles_search, url: articles_path, method: :get do |f|
    - [[:title, '記事タイトル'],
      [:body, '記事本文'],
      [:comment_body, 'コメント本文']].each do |(key, name)|
      .col-xs-4
        %label= name
        .input-group
          = f.text_field key, class: 'form-control'
          %span.input-group-btn
            %button.btn.btn-default{ type: 'submit' }
              %i.fa.fa-search

app/views/articles/_tag_fields.html.haml
.nested-fields
  .row.form-group
    .col-sm-5
      = f.text_field :name, class: 'form-control'
    .col-sm-2
      = f.number_field :display_order, class: 'form-control'
    .col-sm-5
      = link_to_remove_association f do
        %button.btn.btn-default
          %i.fa.fa-trash

app/views/articles/edit.html.haml
.row
  .col-xs-8.col-xs-offset-2
    %h2 記事の編集
    = render 'form', article: @article

app/views/articles/index.html.haml
%h2 記事一覧
.row
  .col-xs-12
    .box
      .box-header
        %h3.box-title= '記事検索'
      .box-body
        = render 'search_form', articles_search: @articles_search
      .box-header
        %h3.box-title= '記事一覧'
        .pull-right
          = link_to '記事を追加', new_article_path, class: 'btn btn-primary'
      .box-body
        - if @articles.present?
          %table.table.table.table-striped.table-hover
            %tr
              %th.text-center
                記事ID
                = render 'order_link', form_object: @articles_search, url_method: :articles_path, order_by: :id
              %th.text-center
                タイトル
                = render 'order_link', form_object: @articles_search, url_method: :articles_path, order_by: :title
              %th.text-center
                内容
                = render 'order_link', form_object: @articles_search, url_method: :articles_path, order_by: :body
              %th.text-center
                = Article.human_attribute_name(:user_id)
              %th.text-center コメント数
              %th タグ
              %th.text-center
                作成日
                = render 'order_link', form_object: @articles_search, url_method: :articles_path, order_by: :created_at
              %th.text-center
                更新日
                = render 'order_link', form_object: @articles_search, url_method: :articles_path, order_by: :updated_at
              %th
              %th
              %th
            - @articles.each do |article|
              %tr
                %td.text-center= article.id
                %td= article.title
                %td= truncate(article.body)
                %td= article.user.email
                %td.text-right= article.comments.count
                %td= article.tags.pluck(:name).join(',')
                %td= l article.created_at
                %td= l article.updated_at
                %td.text-center= link_to '編集', edit_article_path(article)
                %td.text-center= link_to '詳細', article_path(article)
                %td.text-center= link_to '削除', article_path(article), method: :delete, data: { confirm: '本当に削除しますか？' }

        - else
          %p 記事はありません
      .box-body
        = paginate @articles

app/views/articles/new.html.haml
.row
  .col-xs-8.col-xs-offset-2
    %h2 記事の登録
    = render 'form', article: @article

app/views/articles/show.html.haml
%h2 記事「#{@article.title}」
.row
  .col-xs-12
    .box
      .box-body
        %dl.dl-horizontal
          %dt= Article.human_attribute_name(:id)
          %dd= @article.id
          %dt= Article.human_attribute_name(:title)
          %dd= @article.title
          %dt= Article.human_attribute_name(:body)
          %dd= simple_format(h(@article.body))
          %dt= Article.human_attribute_name(:user_id)
          %dd= @article.user.email
          %dt= Article.human_attribute_name(:image)
          %dd
            - if @article.image.attached?
              = image_tag @article.image
          %dt コメント数
          %dd= @article.comments.count
          %dt タグ
          %dd= @article.tags.pluck(:name).join(',')
          %dt= Article.human_attribute_name(:created_at)
          %dd= l @article.created_at
          %dt= Article.human_attribute_name(:updated_at)
          %dd= l @article.updated_at
    .box
      .box-header
        %h3.box-title コメント一覧
      .box-body
        - if @article.comments.present?
          %table.table.table.table-striped.table-hover
            %tr
              %th.text-center= Comment.human_attribute_name(:id)
              %th.text-center= Comment.human_attribute_name(:body)
              %th.text-center= Comment.human_attribute_name(:created_at)
              %th.text-center= Comment.human_attribute_name(:updated_at)
            - @article.comments.each do |comment|
              %tr
                %td.text-center= comment.id
                %td= simple_format(h(comment.body))
                %td= l comment.created_at
                %td= l comment.updated_at
        - else
          コメントがありません
    = link_to '戻る', articles_path, class: 'btn btn-default'

app/views/front/articles/index.html.haml
%ol.breadcrumb
  %li
    = link_to root_path do
      %span.glyphicon.glyphicon-home
      %span.breadcrumb-link ホーム
  %li.active 記事一覧
.alert.alert-info
  記事一覧がリニューアルしました！
.row
  .col-md-7.col-md-offset-1
    .box
      .box-body
        - @articles.each do |article|
          .item-container
            - if article.image.attached?
              = image_tag article.image, class: 'item-image'
            .item-body
              %span.item-info.text-muted #{article.user.email}が#{l article.created_at.to_date}に投稿
              %span.item-tags
                - article.tags.each do |tag|
                  .item-label.label.label-warning
                    = tag.name
              .item-title-section
                = link_to article.title, article_path(article), class: 'item-title'

            .item-status.text-muted
              %i.fa.fa-comment-o
              = article.comments.count
  .col-md-3
    .panel.panel-primary
      .panel-heading
        .text-center アカウント情報
      .panel-body
        .row
          .col-md-6
            .article__account-info.text-center
              .article__account-count.info-box-number
                = current_user.articles.count
              .article__account-colmun.text-muted
                記事
          .col-md-6
            .article__account-info.text-center
              .article__account-count.info-box-number
                = Comment.where(article: current_user.articles).count
              .article__account-colmun.text-muted
                コメント

app/views/home/index.html.haml
%h2 ホーム
.row
  .col-xs-12
    .box
      - if @comments.present?
        %table.table.table-bordered
          %tr
            %th 記事タイトル
            %th コメント内容
          - @comments.each do |comment|
            %tr
              %td= comment.article.title
              %td= comment.body

      - else
        %p データはありません
#home-comment-vue
#home-vue

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render partial: 'application/head_tag_content'
    %title QiitanTraining
    %script{src: "https://code.jquery.com/jquery-3.4.1.min.js"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  %body.hold-transition.skin-blue.fixed
    .wrapper
      = render partial: 'application/nav_header'
      = render partial: 'application/sidebar'
      .content-wrapper
        = render partial: 'application/notice_alert'
        %section.content.container-fluid
          = yield
  = yield :javascript_tag

app/views/layouts/unauthenticated.html.haml
!!!
%html
  %head
    = render partial: 'application/head_tag_content'
    %title QiitanTraining
    = javascript_pack_tag 'application', media: 'all'
    = stylesheet_pack_tag 'application', media: 'all'
    = csrf_meta_tags

  %body.hold-transition.login-page
    = yield

:javascript
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-yellow',
      radioClass: 'iradio_square-yellow',
      increaseArea: '20%'
    });
  });

app/views/vue/articles/edit.html.haml
#edit-article-vue{ data: { article_id: @article.id }}

app/views/vue/articles/index.html.haml
#articles-vue{ data: { articles: @articles.to_json(methods: %i[author_email short_body comment_count]) } }
= javascript_pack_tag 'article'

app/views/vue/articles/new.html.haml
#new-article-vue{ data: { user_id: current_user.id }}

app/views/vue/articles/show.html.haml
#article-vue

app/views/vue/comments/index.html.haml
#comments-vue{ data: { article_id: @article.id }}
= javascript_pack_tag 'comment'